#!/usr/bin/env bash
# Install nginx on your web-01

# Update the package lists
sudo apt-get update

# Install Nginx package
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

# Create a temporary HTML file with the desired content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Sets Nginx to listen on port 80 and serve files from the /etc/nginx/html directory.
printf %s "server {
     listen      80;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Restarts the Nginx service to apply the configuration changes.
service nginx restart
