#!/usr/bin/env bash
# client configuration

Host *
  PasswordAuthentication no
  IdentityFile ~/.ssh/school
  SendEnv LANG LC_*
  HashKnownHosts no
  GSSAPIAuthentication yes
  GSSAPIDelegateCredentials no
